---
range:
  # 備份文章編號範圍
  min: 61078
  max: 62000

interval:
  routine:
    # 正常狀況下，兩筆備份的間隔時間範圍，單位毫秒
    min: 15000
    max: 40000
  exception: 
    # 遭遇 429 等非預期狀態，額外等待時間範圍，單位毫秒
    min: 300000
    max: 600000
...